include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "pubspec.lock"
    - "pubspec.yaml"
    - "lib/firebase_options.dart"
    - "lib/**/*.g.dart"
    - "android/**"

linter:
  rules:
    one_member_abstracts: false
    public_member_api_docs: false
    no_default_cases: false
    no_runtimeType_toString: false
    avoid_positional_boolean_parameters: false
    use_if_null_to_convert_nulls_to_bools: false
    avoid_setters_without_getters: false
