include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "pubspec.lock"
    - "pubspec.yaml"
    - "lib/firebase_options.dart"
    - "lib/**/*.g.dart"
    - "android/**"

linter:
  rules:
    one_member_abstracts: false
