name: soft_converter
description: Convert some videos and images to some formats

homepage: https://softyes.com.br
repository: https://github.com/softyesti/soft_converter

platforms:
  windows:
  macos:
  linux:

topics:
  - converter
  - image
  - video
  - ffmpeg
  - cwebp

version: 0.4.0

environment:
  sdk: ^3.12.1
  flutter: ">=3.44.1"

dependencies:
  http: ^1.6.0
  path: ^1.9.1
  hooks: ^2.0.2
  archive: ^4.0.9
  code_assets: ^1.2.1
  data_assets: ^0.20.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.1.0
  very_good_analysis: ^10.2.0
